// -------------------- Rule action responses --------------------

const baseURL = process.env.BASE_URL;

module.exports = {
  rule_typehead_response: {
    header: "List of messages",
    items: [
      {
        icon_url: "https://example.com/icon.png",
        subtitle: "Subtitle",
        title: "Title",
        value: "Typeahead",
      },
      {
        icon_url: "https://example.com/icon.png",
        subtitle: "Subtitle 2",
        title: "Title 2",
        value: "Typeahead",
      },
    ],
  },
  rule_action_response: {
    action_result: "ok",
    error: "That resource no longer exists",
    resources_created: [
      {
        error: "No resource matched that input",
        resource_name: "Build the Thing",
        resource_url: "https://example.atlassian.net/browse/CP-1",
      },
    ],
  },
  rule_metadata_response: {
    metadata: {
      fields: [
        {
          error: "Please review and change your input",
          id: "field-1",
          is_required: true,
          is_watched: true,
          name: "Checkbox",
          options: [
            {
              id: "opt-in",
              label: "Opt in",
            },
          ],
          type: "checkbox",
          value: ["opt-in"],
        },
        {
          error: "Please review and change your input",
          id: "field-2",
          is_required: true,
          is_watched: true,
          name: "Date",
          placeholder: "Please select a date",
          type: "date",
        },
        {
          error: "Please review and change your input",
          id: "field-3",
          is_required: true,
          is_watched: true,
          name: "Datetime",
          placeholder: "Please select a datetime",
          type: "datetime",
        },
        {
          error: "Please review and change your input",
          id: "field-4",
          is_required: true,
          is_watched: true,
          name: "Dropdown",
          options: [
            {
              icon_url: "https://example.com/red.png",
              id: "red",
              label: "Red",
            },
          ],
          type: "dropdown",
          value: "red",
          width: "full",
        },
        {
          error: "Please review and change your input",
          id: "field-5",
          is_required: true,
          is_watched: true,
          name: "Multiline Text",
          placeholder: "Enter the full title of the resource here",
          type: "multi_line_text",
          value: "Multiline Text",
        },
        {
          error: "Please review and change your input",
          id: "field-6",
          is_required: true,
          is_watched: true,
          name: "Radio Button",
          options: [
            {
              id: "blue",
              label: "Blue",
              sub_label: "#0000FF",
            },
          ],
          type: "radio_button",
          value: "blue",
        },
        {
          error: "Please review and change your input",
          id: "field-7",
          is_required: true,
          is_watched: true,
          name: "Rich Text",
          placeholder: "Enter the full title of the resource here",
          type: "rich_text",
          value: "Rich Text",
        },
        {
          error: "Please review and change your input",
          id: "field-8",
          is_required: true,
          is_watched: true,
          name: "Single Line Text",
          placeholder: "Enter the full title of the resource here",
          type: "single_line_text",
          value: "Single Line Text",
          width: "full",
        },
        {
          id: "field-9",
          name: "Static Text",
          type: "static_text",
        },
        {
          error: "Please review and change your input",
          id: "field-10",
          is_required: true,
          is_watched: true,
          name: "Typeahead",
          type: "typeahead",
          typeahead_url: `${baseURL}/rule/typeahead`,
          value: {
            icon_url: "https://example.com/icon.png",
            subtitle: "Subtitle",
            title: "Title",
            value: "Typeahead",
          },
          width: "full",
        },
      ],
      on_change_callback: `${baseURL}/rule/on_change`,
      on_submit_callback: `${baseURL}/rule/on_submit`,
      submit_button_text: "Submit",
      title: "Rule Metadata",
    },
    template: "form_metadata_v0",
  },
  rule_on_change_response: {
    metadata: {
      fields: [
        {
          error: "Please review and change your input",
          id: "field-1",
          is_required: true,
          is_watched: true,
          name: "Checkbox",
          options: [
            {
              id: "opt-in",
              label: "Opt in",
            },
          ],
          type: "checkbox",
          value: ["opt-in"],
        },
        {
          error: "Please review and change your input",
          id: "field-2",
          is_required: true,
          is_watched: true,
          name: "Date",
          placeholder: "Please select a date",
          type: "date",
          value: "2022-01-01",
        },
        {
          error: "Please review and change your input",
          id: "field-3",
          is_required: true,
          is_watched: true,
          name: "Datetime",
          placeholder: "Please select a datetime",
          type: "datetime",
          value: "2023-01-01T00:00:00.000Z",
        },
        {
          error: "Please review and change your input",
          id: "field-4",
          is_required: true,
          is_watched: true,
          name: "Dropdown",
          options: [
            {
              icon_url: "https://example.com/red.png",
              id: "red",
              label: "Red",
            },
          ],
          type: "dropdown",
          value: "red",
          width: "full",
        },
        {
          error: "Please review and change your input",
          id: "field-5",
          is_required: true,
          is_watched: true,
          name: "Multiline Text",
          placeholder: "Enter the full title of the resource here",
          type: "multi_line_text",
          value: "Multiline Text",
        },
        {
          error: "Please review and change your input",
          id: "field-6",
          is_required: true,
          is_watched: true,
          name: "Radio Button",
          options: [
            {
              id: "blue",
              label: "Blue",
              sub_label: "#0000FF",
            },
          ],
          type: "radio_button",
          value: "blue",
        },
        {
          error: "Please review and change your input",
          id: "field-7",
          is_required: true,
          is_watched: true,
          name: "Rich Text",
          placeholder: "Enter the full title of the resource here",
          type: "rich_text",
          value: "Rich Text",
        },
        {
          error: "Please review and change your input",
          id: "field-8",
          is_required: true,
          is_watched: true,
          name: "Single Line Text",
          placeholder: "Enter the full title of the resource here",
          type: "single_line_text",
          value: "Single Line Text",
          width: "full",
        },
        {
          id: "field-9",
          name: "Static Text",
          type: "static_text",
        },
        {
          error: "Please review and change your input",
          id: "field-10",
          is_required: true,
          is_watched: true,
          name: "Typeahead",
          type: "typeahead",
          typeahead_url: `${baseURL}/rule/typeahead`,
          value: {
            icon_url: "https://example.com/icon.png",
            subtitle: "Subtitle",
            title: "Title",
            value: "Typeahead",
          },
          width: "full",
        },
      ],
      on_change_callback: `${baseURL}/rule/on_change`,
      on_submit_callback: `${baseURL}/rule/on_submit`,
      submit_button_text: "Submit",
      title: "Rule On Change",
    },
    template: "form_metadata_v0",
  },
};
